import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { posts } from "@/data";
import { useState } from "react";
import Post from "@/components/Post";

export default function Home() {
  const [page, setPage] = useState(1);
  const [myPosts, setMyPosts] = useState(posts.slice((page - 1) * 4, 4));

  return (
    <>
      <Head>
        <title>Candy posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.posts}>
          {myPosts.map((post) => {
            return <Post key={post.id} post={post} />;
          })}
        </div>
      </main>
    </>
  );
}
