import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { posts } from "@/data";
import { useEffect, useState } from "react";
import Post from "@/components/Post";
import Pagination from "@/components/Pagination";
import { useGlobalContext } from "@/context/appContext";

export default function Home() {
  const { state } = useGlobalContext();
  const { page, limit } = state;
  const [myPosts, setMyPosts] = useState(
    posts.slice((page - 1) * limit, (page - 1) * limit + limit)
  );
  const numOfPages = Math.ceil(posts.length / limit);

  useEffect(() => {
    setMyPosts(posts.slice((page - 1) * limit, (page - 1) * limit + limit));
  }, [page]);

  return (
    <>
      <Head>
        <title>Candy posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.posts}>
          {myPosts.map((post) => {
            return <Post key={post.id} post={post} />;
          })}
        </div>
        <Pagination numOfPages={numOfPages} />
      </main>
    </>
  );
}
