export const posts = [
  {
    id: 1,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 2,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 3,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 4,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 5,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 6,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 7,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 8,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 9,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 10,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 11,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 12,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 13,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 14,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 15,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 16,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 17,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 18,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
  {
    id: 19,
    title: "This is a title ",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facili  deserunt tempora delectus molestias sint quos iusto optio et dolorem porro possimus nobis repellendus amet voluptatem repellat enim magnam? Laboriosam quo nemo odio provident? Fugiat asperiores estdoloremque illum velit vel",
    createdAt: "September 26, 2019",
  },
];
